version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: skillhub-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: skillhub
      MYSQL_USER: skillhub_user
      MYSQL_PASSWORD: skillhub_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # SQL init file removed - schema is initialized by backend
    networks:
      - skillhub-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    image: dilipravikumar619/skillhub-backend:latest
    container_name: skillhub-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/skillhub
      - SPRING_DATASOURCE_USERNAME=skillhub_user
      - SPRING_DATASOURCE_PASSWORD=skillhub_pass
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_THUMBNAILS=${AWS_S3_BUCKET_THUMBNAILS}
      - AWS_S3_BUCKET_VIDEOS=${AWS_S3_BUCKET_VIDEOS}
      - JWT_SECRET=${JWT_SECRET:-default-secret-key}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_ENABLED=${MAIL_ENABLED}
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - skillhub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Angular Frontend
  frontend:
    image: dilipravikumar619/skillhub-frontend:latest
    container_name: skillhub-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - skillhub-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: skillhub-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - skillhub-network
    depends_on:
      - backend
    restart: unless-stopped

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: skillhub-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - skillhub-network
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  skillhub-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
